### ISSUE TITLE
Not able to install in localmachine

### ISSUE THREAD

**Issue by Aju100** [shitalluitel/LibraryManagementSystem#3]
### Machine
- python3
- ubuntu

### To check error
- Install all the requirements libraries
- Activate the python  environment
- run python manage.py runserver

### Output
`/home/aju/.local/share/virtualenvs/LibraryManagementSystem-PGab2cH-/lib/python3.7/site-packages/environ/environ.py:639: UserWarning: Error reading /home/aju/Desktop/opensource/LibraryManagementSystem/.env - if you're not configuring your environment separately, check this.
  "environment separately, check this." % env_file)
Traceback (most recent call last):
  File "/home/aju/.local/share/virtualenvs/LibraryManagementSystem-PGab2cH-/lib/python3.7/site-packages/environ/environ.py", line 273, in get_value
    value = self.ENVIRON[var]
  File "/home/aju/.local/share/virtualenvs/LibraryManagementSystem-PGab2cH-/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'DB_HOST'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/aju/.local/share/virtualenvs/LibraryManagementSystem-PGab2cH-/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/aju/.local/share/virtualenvs/LibraryManagementSystem-PGab2cH-/lib/python3.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/aju/.local/share/virtualenvs/LibraryManagementSystem-PGab2cH-/lib/python3.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/aju/.local/share/virtualenvs/LibraryManagementSystem-PGab2cH-/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 61, in execute
    super(Command, self).execute(*args, **options)
  File "/home/aju/.local/share/virtualenvs/LibraryManagementSystem-PGab2cH-/lib/python3.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/aju/.local/share/virtualenvs/LibraryManagementSystem-PGab2cH-/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 72, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/home/aju/.local/share/virtualenvs/LibraryManagementSystem-PGab2cH-/lib/python3.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/aju/.local/share/virtualenvs/LibraryManagementSystem-PGab2cH-/lib/python3.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/aju/.local/share/virtualenvs/LibraryManagementSystem-PGab2cH-/lib/python3.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/aju/.local/share/virtualenvs/LibraryManagementSystem-PGab2cH-/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/aju/Desktop/opensource/LibraryManagementSystem/LibraryManagementSystem/settings.py", line 121, in <module>
    'HOST': env('DB_HOST'),
  File "/home/aju/.local/share/virtualenvs/LibraryManagementSystem-PGab2cH-/lib/python3.7/site-packages/environ/environ.py", line 123, in __call__
    return self.get_value(var, cast=cast, default=default, parse_default=parse_default)
  File "/home/aju/.local/share/virtualenvs/LibraryManagementSystem-PGab2cH-/lib/python3.7/site-packages/environ/environ.py", line 277, in get_value
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: Set the DB_HOST environment variable
`

**Comment by Aju100** [comment]
@shitalluitel

**Comment by shitalluitel** [comment]
configure your .env file according to sample.env file within project.

**Comment by Aju100** [comment]
@shitalluitel  sure.
